# Generated by Django 5.1 on 2024-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_remove_orderitem_product_alter_shippingaddress_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[(1, "visa"), (2, "cache"), (3, "fawry")],
                default="visa",
                max_length=100,
            ),
        ),
    ]
