# Generated by Django 5.1 on 2024-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[(1, "visa"), (2, "cache"), (3, "fawry")], default="visa"
            ),
        ),
    ]
